
export const planets: Planet[] = [
    {
        name: 'Меркурий',
        img: './assets/images/planets/Mercury.jpg',
        imgSmall: './assets/images/planets/Mercury.jpg',
        satellite: 0,
        temperature: 67,
        radius: 2439,
    },
    {
        name: 'Венера',
        img: './assets/images/planets/Venus.jpg',
        imgSmall: './assets/images/planets/Venus.jpg',
        satellite: 0,
        temperature: 464,
        radius: 6051,
    },
    {
        name: 'Земля',
        img: './assets/images/planets/Earth.jpg',
        imgSmall: './assets/images/planets/Earth.jpg',
        satellite: 1,
        temperature: 14,
        radius: 6371,
    },
    {
        name: 'Марс',
        img: './assets/images/planets/Mars.jpg',
        imgSmall: './assets/images/planets/Mars.jpg',
        satellite: 2,
        temperature: -63,
        radius: 3396,
    },
    {
        name: 'Юпитер',
        img: './assets/images/planets/Jupiter.jpg',
        imgSmall: './assets/images/planets/Jupiter.jpg',
        satellite: 67,
        temperature: 16000,
        radius: 69911,
    },
    {
        name: 'Сатурн',
        img: './assets/images/planets/Saturn.jpg',
        imgSmall: './assets/images/planets/Saturn.jpg',
        satellite: 62,
        temperature: -178,
        radius: 58232,
    },
    {
        name: 'Уран',
        img: './assets/images/planets/Uranus.jpg',
        imgSmall: './assets/images/planets/Uranus.jpg',
        satellite: 27,
        temperature: -224,
        radius: 25362,
    },
    {
        name: 'Нептун',
        img: './assets/images/planets/Neptune.jpg',
        imgSmall: './assets/images/planets/Neptune.jpg',
        satellite: 14,
        temperature: -218,
        radius: 24622,
    },
];
